local base = (...):gsub('[^%.]+.[^%.]+$', '')
testCoverage = require 'coverage-config'
local T = require(base .. 'lib.simple-test')

T.check(require(base .. 'test.scene-tree'))
T.check(require(base .. 'test.layer'))
T.check(require(base .. 'test.depth-list'))
T.check(require(base .. 'test.scene-tree-draw-order'))
T.check(require(base .. 'test.random'))
T.check(require(base .. 'test.input'))
T.check(require(base .. 'test.physics'))
T.check(require(base .. 'test.physics-with-body'))
T.check(require(base .. 'test.lerpdt'))
T.check(require(base .. 'test.gui-node'))
T.check(require(base .. 'test.gui-row-col'))
T.check(require(base .. 'test.gui-sprite'))
T.check(require(base .. 'test.gui-slice'))
T.check(require(base .. 'test.gui-mask'))
T.check(require(base .. 'test.gui-text'))

T.plan()
